const R=304.8,$=id=>document.getElementById(id);
const map=L.map('map').setView([27.95,-82.46],10);
let base=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}).addTo(map),baseFallback=false;
base.on('tileerror',()=>{if(baseFallback)return;baseFallback=true;map.removeLayer(base);base=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map)});
const schoolLayer=L.layerGroup().addTo(map),restrictedLayer=L.layerGroup().addTo(map),routeLayer=L.layerGroup().addTo(map),markerLayer=L.layerGroup().addTo(map),gpsLayer=L.layerGroup().addTo(map);
let schools=[],restrictedPlaces=[],SO=null,SD=null,AR=null,DEST=null,watch=null,timers={},lastReroute=0,isRerouting=false;
let activeOrigin=null;
function status(t,c=''){$('st').className='status '+c;$('st').textContent=t}
function progress(p,s,d=''){$('prog').style.display='block';$('fill').style.width=Math.max(0,Math.min(100,p))+'%';$('pct').textContent=Math.round(p)+'%';$('stage').textContent=s;$('detail').textContent=d}
async function j(url,opt={},ms=16000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...opt,signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch(e){if(e.name==='AbortError')throw Error('Request timed out');throw e}finally{clearTimeout(t)}}
async function searchAddr(q){return j('https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=6&countrycodes=us&q='+encodeURIComponent(q),{},10000)}
function labelAddr(x){const a=x.address||{},l1=[a.house_number,a.road].filter(Boolean).join(' ')||x.display_name.split(',')[0],l2=[a.city||a.town||a.village||a.county,a.state,a.postcode].filter(Boolean).join(', ');return[l1,l2]}
function auto(k){const inp=$(k),box=$(k+'s');inp.oninput=()=>{k==='o'?SO=null:SD=null;clearTimeout(timers[k]);const q=inp.value.trim();if(q.length<3){box.style.display='none';return}timers[k]=setTimeout(async()=>{try{const list=await searchAddr(q);box.innerHTML='';for(const x of list){const [a,b]=labelAddr(x),e=document.createElement('div');e.className='item';e.innerHTML='<b>'+a+'</b><small>'+b+'</small>';e.onclick=()=>{const v={lat:+x.lat,lon:+x.lon,label:x.display_name};k==='o'?SO=v:SD=v;inp.value=a+(b?', '+b:'');box.style.display='none'};box.appendChild(e)}box.style.display=list.length?'block':'none'}catch(_){box.style.display='none'}},250)}}
auto('o');auto('d');document.addEventListener('click',e=>{if(!e.target.closest('.field')){$('os').style.display='none';$('ds').style.display='none'}});
async function resolve(q,s){if(s)return s;const x=await searchAddr(q);if(!x.length)throw Error('Address not found');return{lat:+x[0].lat,lon:+x[0].lon,label:x[0].display_name}}
function gpsOnce(){return new Promise((res,rej)=>{if(!navigator.geolocation)return rej(Error('GPS unavailable'));navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,lon:p.coords.longitude,label:'Current location'}),e=>rej(Error(e.message||'Location unavailable')),{enableHighAccuracy:true,timeout:12000,maximumAge:3000})})}
async function route(a,b,wps=[],alts=false){const pts=[a,...wps,b],c=pts.map(p=>p.lon+','+p.lat).join(';'),tail='/'+c+'?overview=full&geometries=geojson&steps=true&alternatives='+(alts?'true':'false'),urls=['https://router.project-osrm.org/route/v1/driving'+tail,'https://routing.openstreetmap.de/routed-car/route/v1/driving'+tail];let err=[];for(const u of urls){try{const d=await j(u,{},16000);if(d.routes?.length)return d.routes;err.push('no route')}catch(e){err.push(e.message)}}throw Error('Routing service unavailable: '+err.join(' / '))}
const PUB='https://nces.ed.gov/opengis/rest/services/K12_School_Locations/EDGE_GEOCODE_PUBLICSCH_2425/MapServer/0/query',PRI='https://nces.ed.gov/opengis/rest/services/K12_School_Locations/EDGE_GEOCODE_PRIVATESCH_2324/MapServer/0/query';
const REGIONS={tampa:{name:'Tampa Bay',box:{xmin:-82.90,ymin:27.45,xmax:-81.85,ymax:28.85}},orlando:{name:'Orlando',box:{xmin:-81.85,ymin:27.95,xmax:-80.80,ymax:29.05}}};
const CACHE_KEY='schoolZoneGpsV10RegionCache';const CACHE_MS=7*24*60*60*1000;let regionCache={};let regionPrefetchPromise=null;
function cacheRead(){try{const x=JSON.parse(localStorage.getItem(CACHE_KEY)||'{}');if(x.ts&&Date.now()-x.ts<CACHE_MS)return x.regions||{}}catch(_){}return{}}
function cacheWrite(){try{localStorage.setItem(CACHE_KEY,JSON.stringify({ts:Date.now(),regions:regionCache}))}catch(_){}}
function boxIntersects(a,b){return a.xmin<=b.xmax&&a.xmax>=b.xmin&&a.ymin<=b.ymax&&a.ymax>=b.ymin}
function routeBox(r,pad=1.5){const c=r.geometry.coordinates;let x1=999,x2=-999,y1=99,y2=-99;for(const p of c){x1=Math.min(x1,p[0]);x2=Math.max(x2,p[0]);y1=Math.min(y1,p[1]);y2=Math.max(y2,p[1])}const mid=(y1+y2)/2,dy=pad/111,dx=pad/(111*Math.max(.2,Math.cos(mid*Math.PI/180)));return{xmin:x1-dx,ymin:y1-dy,xmax:x2+dx,ymax:y2+dy}}
async function ncesBox(url,b,type){const q=new URLSearchParams({where:"STATE='FL'",geometry:`${b.xmin},${b.ymin},${b.xmax},${b.ymax}`,geometryType:'esriGeometryEnvelope',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:type==='public'?'NCESSCH,NAME,LAT,LON':'PPIN,NAME,LAT,LON',returnGeometry:'true',outSR:'4326',f:'json'}),d=await j(url+'?'+q.toString(),{},16000);if(d.error)throw Error(d.error.message);return(d.features||[]).map((f,i)=>{const a=f.attributes||{},g=f.geometry||{},lat=Number.isFinite(+a.LAT)?+a.LAT:+g.y,lon=Number.isFinite(+a.LON)?+a.LON:+g.x;return Number.isFinite(lat)&&Number.isFinite(lon)?{id:type+':'+(a.NCESSCH||a.PPIN||i),name:a.NAME||'School',lat,lon,type}:null}).filter(Boolean)}
function makeAnchors(s){const pt=turf.point([s.lon,s.lat]),out=[];for(const dist of [.50,.78])for(let br=0;br<360;br+=45){const p=turf.destination(pt,dist,br,{units:'kilometers'}).geometry.coordinates;out.push({lon:p[0],lat:p[1],bearing:br,dist})}return out}
function enrichSchools(list){return list.map(s=>({...s,anchors:s.anchors||makeAnchors(s)}))}
async function loadRegion(name){const reg=REGIONS[name];if(regionCache[name]?.schools?.length)return regionCache[name].schools;const z=await Promise.allSettled([ncesBox(PUB,reg.box,'public'),ncesBox(PRI,reg.box,'private')]);const all=[];for(const x of z)if(x.status==='fulfilled')all.push(...x.value);if(!all.length)throw Error(reg.name+' school preload failed');const m=new Map;for(const s of all)m.set(s.id,s);const list=enrichSchools([...m.values()]);regionCache[name]={schools:list};cacheWrite();return list}
async function prefetchRegions(){regionCache=cacheRead();const ready=Object.keys(REGIONS).filter(k=>regionCache[k]?.schools?.length);if(ready.length===2){$('cacheState').textContent='Tampa + Orlando cache ready';return}try{await Promise.allSettled(Object.keys(REGIONS).map(k=>loadRegion(k)));const n=Object.keys(REGIONS).filter(k=>regionCache[k]?.schools?.length).length;$('cacheState').textContent=n===2?'Tampa + Orlando cache ready':n+' region cache ready'}catch(_){$('cacheState').textContent='Regional cache partial'}}
regionPrefetchPromise=prefetchRegions();
function nearRoute(s,r,maxKm=8){try{return turf.pointToLineDistance(turf.point([s.lon,s.lat]),turf.lineString(r.geometry.coordinates),{units:'kilometers'})<=maxKm}catch(_){return true}}
async function loadSchools(r){const rb=routeBox(r,3),regionNames=Object.keys(REGIONS).filter(k=>boxIntersects(rb,REGIONS[k].box));let all=[];if(regionNames.length){progress(32,'Using regional cache','Tampa / Orlando school data');await Promise.race([regionPrefetchPromise,new Promise(res=>setTimeout(res,2600))]);for(const k of regionNames){if(regionCache[k]?.schools)all.push(...regionCache[k].schools)}if(all.length){const m=new Map;for(const s of all)if(nearRoute(s,r,8))m.set(s.id,s);return[...m.values()]}}progress(34,'Loading schools','Route is outside cached metro coverage');const z=await Promise.allSettled([ncesBox(PUB,rb,'public'),ncesBox(PRI,rb,'private')]);for(const x of z)if(x.status==='fulfilled')all.push(...x.value);if(!all.length)throw Error('School databases unavailable');const m=new Map;for(const s of enrichSchools(all))m.set(s.id,s);return[...m.values()]}
function zone(s){return turf.buffer(turf.point([s.lon,s.lat]),R/1000,{units:'kilometers',steps:20})}
function originExempt(s){if(!activeOrigin)return false;try{return turf.booleanPointInPolygon(turf.point([activeOrigin.lon,activeOrigin.lat]),zone(s))}catch(_){return false}}
function hitList(r){if(!$('avoid').checked)return[];const line=turf.lineString(r.geometry.coordinates);return schools.filter(s=>{if(originExempt(s))return false;try{return turf.booleanIntersects(line,zone(s))}catch(_){return false}})}