function restrictedBBox(r,padKm=1.2){return routeBox(r,padKm)}
async function overpassRestricted(r){if(!$('restricted').checked)return[];const b=restrictedBBox(r),q=`[out:json][timeout:8];(nwr["amenity"~"^(police|courthouse|prison|university|college)$"](${b.ymin},${b.xmin},${b.ymax},${b.xmax});nwr["aeroway"="terminal"](${b.ymin},${b.xmin},${b.ymax},${b.xmax}););out center tags;`;const body='data='+encodeURIComponent(q),eps=['https://overpass.kumi.systems/api/interpreter','https://overpass-api.de/api/interpreter'];let data=null;for(const ep of eps){try{data=await j(ep,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body},9000);break}catch(_){}}if(!data)return[];return(data.elements||[]).map(e=>{const lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon,t=e.tags||{};if(lat==null||lon==null)return null;const kind=t.amenity||t.aeroway||'restricted';return{name:t.name||kind,lat,lon,kind}}).filter(Boolean)}
function restrictedLabel(kind){return({police:'Police facility',courthouse:'Courthouse',prison:'Jail / prison',university:'University',college:'College',terminal:'Airport terminal'})[kind]||'Potential restricted location'}
function drawRestricted(list){restrictedLayer.clearLayers();for(const p of list){L.circleMarker([p.lat,p.lon],{radius:5,color:'#fff',weight:2,fillColor:'#8b1e1e',fillOpacity:1}).bindPopup('<b>'+p.name+'</b><br>'+restrictedLabel(p.kind)+'<br><small>Potential firearm-restricted location. No distance buffer applied; verify current law and site rules.</small>').addTo(restrictedLayer)}}
function destinationWarning(dest,list){let nearest=null,dist=Infinity;for(const p of list){const d=turf.distance(turf.point([dest.lon,dest.lat]),turf.point([p.lon,p.lat]),{units:'kilometers'})*1000;if(d<dist){dist=d;nearest=p}}if(nearest&&dist<180)return 'Destination is near '+nearest.name+' ('+restrictedLabel(nearest.kind)+'). Verify firearm restrictions before entering.';return''}
async function loadRestrictedAsync(r,dest){$('destWarning').textContent='';if(!$('restricted').checked){restrictedLayer.clearLayers();return}try{const list=await overpassRestricted(r);restrictedPlaces=list;drawRestricted(list);const w=destinationWarning(dest,list);if(w){$('destWarning').innerHTML='<span class="red">'+w+'</span>'}}catch(_){}}
async function build(fromGps=false){const oq=$('o').value.trim(),dq=$('d').value.trim();if(!dq)return status('Enter a destination.','err');$('go').disabled=true;$('sum').style.display='none';$('nav').style.display='none';$('fill').style.background='#1a73e8';try{progress(8,'Resolving route','Checking origin and destination');const a=fromGps||!oq||oq==='Current location'?await gpsOnce():await resolve(oq,SO),b=await resolve(dq,SD);SO=a;DEST=b;activeOrigin=a;if(fromGps||!oq)$('o').value='Current location';progress(20,'Normal route','Getting route alternatives');const alternatives=await route(a,b,[],true);progress(30,'School data','Using preloaded Tampa / Orlando cache when possible');schools=await loadSchools(alternatives[0]);progress(48,'Scanning alternatives',schools.length+' nearby schools ready');const out=await avoidRoute(a,b,alternatives),r=out.r,n=out.n;AR=r;progress(95,'Drawing route',n?'Best route still has conflicts':'School crossings cleared');drawRoute(r,a,b,n);$('sumMain').textContent=time(r.duration)+' · '+miles(r.distance);$('sumSub').innerHTML=n?'<span class="orange">Best route found · '+n+' school-zone conflict'+(n===1?'':'s')+' remains · NOT marked safe</span>':'Avoid Schools ON · no detected 1,000 ft school-buffer crossings';$('sum').style.display='block';progress(100,n?'Best available route':'Route ready',n?'Orange route still has detected conflicts':'No detected school-buffer crossings');$('fill').style.background=n?'#f9ab00':'#1a73e8';status(n?'Route shown, but remaining school conflicts are highlighted.':'Route calculated successfully.','ok');loadRestrictedAsync(r,b)}catch(e){status('Could not calculate route: '+e.message,'err');progress(100,'Route failed',e.message);$('fill').style.background='#d93025'}finally{$('go').disabled=false}}
$('go').onclick=()=>build(false);
$('loc').onclick=async()=>{try{const p=await gpsOnce();SO=p;activeOrigin=p;$('o').value='Current location';gpsLayer.clearLayers();L.circleMarker([p.lat,p.lon],{radius:8,color:'#fff',weight:3,fillColor:'#4285f4',fillOpacity:1}).addTo(gpsLayer);map.setView([p.lat,p.lon],15);status('Current GPS location selected.','ok')}catch(e){status(e.message,'err')}};
$('restricted').onchange=()=>{if(!$('restricted').checked){restrictedLayer.clearLayers();$('destWarning').textContent=''}else if(AR&&DEST)loadRestrictedAsync(AR,DEST)};
$('navBtn').onclick=()=>{$('nav').style.display='block';$('navTitle').textContent=AR&&hitList(AR).length?'Best route — conflicts remain':'Navigation';$('navText').textContent='Start GPS to follow your live position.'};
$('exit').onclick=()=>{$('nav').style.display='none';if(watch!==null){navigator.geolocation.clearWatch(watch);watch=null;$('gps').textContent='Start GPS'}};
async function reroute(lat,lon){if(isRerouting||!DEST||Date.now()-lastReroute<15000)return;isRerouting=true;lastReroute=Date.now();try{const a={lat,lon,label:'Current location'};activeOrigin=a;const alternatives=await route(a,DEST,[],true);schools=await loadSchools(alternatives[0]);const out=await avoidRoute(a,DEST,alternatives);AR=out.r;drawRoute(out.r,a,DEST,out.n);$('sumMain').textContent=time(out.r.duration)+' · '+miles(out.r.distance);$('sumSub').innerHTML=out.n?'<span class="orange">Live reroute · '+out.n+' conflict(s) remain</span>':'Live reroute · school buffers cleared';status(out.n?'Live reroute still has detected school-zone conflicts.':'Rerouted from your current GPS location.',out.n?'warn':'ok');loadRestrictedAsync(out.r,DEST)}catch(e){status('Live reroute failed: '+e.message,'err')}finally{isRerouting=false}}
$('gps').onclick=()=>{if(!navigator.geolocation)return status('GPS unavailable.','err');if(watch!==null)return;$('gps').textContent='GPS Active';watch=navigator.geolocation.watchPosition(p=>{const lat=p.coords.latitude,lon=p.coords.longitude;gpsLayer.clearLayers();L.circleMarker([lat,lon],{radius:8,color:'#fff',weight:3,fillColor:'#4285f4',fillOpacity:1}).addTo(gpsLayer);map.setView([lat,lon],16);if(AR){let off=0;try{off=turf.pointToLineDistance(turf.point([lon,lat]),turf.lineString(AR.geometry.coordinates),{units:'kilometers'})*1000}catch(_){}if(off>130)reroute(lat,lon)}},e=>status('GPS error: '+e.message,'err'),{enableHighAccuracy:true,maximumAge:2000,timeout:15000})};