/* v11.4 global-corridor + local-detour routing. No route is accepted with a 1,000 ft school-circle crossing. */
const VALIDATION_RADIUS_M=304.8;
const routeHitCache=new WeakMap();
function yieldBrowser(ms=0){return new Promise(r=>setTimeout(r,ms))}
function metersPerLon(lat){return 111320*Math.cos(lat*Math.PI/180)}
function pointToSegmentMeters(sLon,sLat,aLon,aLat,bLon,bLat){const mx=metersPerLon(sLat),my=110540,ax=(aLon-sLon)*mx,ay=(aLat-sLat)*my,bx=(bLon-sLon)*mx,by=(bLat-sLat)*my,vx=bx-ax,vy=by-ay,vv=vx*vx+vy*vy;if(vv<1e-9)return Math.hypot(ax,ay);let t=-(ax*vx+ay*vy)/vv;t=Math.max(0,Math.min(1,t));return Math.hypot(ax+t*vx,ay+t*vy)}
function routeBoundsFast(r){if(r.__fastBounds)return r.__fastBounds;const c=r.geometry.coordinates;let minLon=Infinity,maxLon=-Infinity,minLat=Infinity,maxLat=-Infinity;for(const p of c){minLon=Math.min(minLon,p[0]);maxLon=Math.max(maxLon,p[0]);minLat=Math.min(minLat,p[1]);maxLat=Math.max(maxLat,p[1])}const b={minLon,maxLon,minLat,maxLat};try{Object.defineProperty(r,'__fastBounds',{value:b,enumerable:false})}catch(_){}return b}
function distanceMeters(a,b){const R0=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R0*Math.asin(Math.min(1,Math.sqrt(h)))}
function schoolHitInfos(r){if(!r)return[];const cached=routeHitCache.get(r);if(cached&&cached.schoolsRef===schools)return cached.hits;const coords=r.geometry.coordinates,b=routeBoundsFast(r),padLat=VALIDATION_RADIUS_M/110540,padLon=VALIDATION_RADIUS_M/Math.max(20000,metersPerLon((b.minLat+b.maxLat)/2)),hits=[];for(const s of schools){if(s.lon<b.minLon-padLon||s.lon>b.maxLon+padLon||s.lat<b.minLat-padLat||s.lat>b.maxLat+padLat)continue;let seg=-1,minDist=Infinity;for(let i=0;i<coords.length-1;i++){const a=coords[i],d=coords[i+1];if(s.lon<Math.min(a[0],d[0])-padLon||s.lon>Math.max(a[0],d[0])+padLon||s.lat<Math.min(a[1],d[1])-padLat||s.lat>Math.max(a[1],d[1])+padLat)continue;const dist=pointToSegmentMeters(s.lon,s.lat,a[0],a[1],d[0],d[1]);minDist=Math.min(minDist,dist);if(dist<=VALIDATION_RADIUS_M){seg=i;break}}if(seg>=0)hits.push({s,segmentIndex:seg,distance:minDist})}hits.sort((a,b)=>a.segmentIndex-b.segmentIndex);routeHitCache.set(r,{schoolsRef:schools,hits});return hits}
function hitList(r){if(!$('avoid').checked||!r)return[];return schoolHitInfos(r).map(x=>x.s)}
function bearing(a,b){const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function destinationPoint(lon,lat,distM,bearingDeg){const R0=6371000,br=bearingDeg*Math.PI/180,p1=lat*Math.PI/180,l1=lon*Math.PI/180,d=distM/R0,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(br)),l2=l1+Math.atan2(Math.sin(br)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return{lon:l2*180/Math.PI,lat:p2*180/Math.PI}}
function interpolate(a,b,t){return{lon:a.lon+(b.lon-a.lon)*t,lat:a.lat+(b.lat-a.lat)*t}}
function shiftPoint(p,heading,offsetM){return destinationPoint(p.lon,p.lat,offsetM,heading)}
async function routeWithWps(a,b,wps){const rs=await route(a,b,wps,false);if(!rs?.length)throw Error('No route returned');return rs[0]}
function routeScore(r){return schoolHitInfos(r).length*1e9+(r.duration||0)}
function corridorPatterns(a,b){const h=bearing(a,b),perp=[h+90,h-90],distance=distanceMeters(a,b),offsets=distance>70000?[5000,9000,14000,21000,30000]:[3500,6500,10000,15000,22000],patterns=[];for(const ph of perp){for(const off of offsets){const p1=shiftPoint(interpolate(a,b,.30),ph,off),p2=shiftPoint(interpolate(a,b,.58),ph,off),p3=shiftPoint(interpolate(a,b,.78),ph,off*.75);patterns.push([p1,p2,p3]);if(off<=15000)patterns.push([shiftPoint(interpolate(a,b,.48),ph,off)])}}return patterns}
async function globalCorridorSearch(a,b,alternatives){let best=alternatives.slice().sort((x,y)=>routeScore(x)-routeScore(y))[0];if(!schoolHitInfos(best).length)return best;const pats=corridorPatterns(a,b);for(let i=0;i<pats.length;i+=2){progress(55+Math.min(20,(i/pats.length)*20),'Searching alternate corridors','Testing a different road corridor · '+(i+1)+'/'+pats.length);const batch=pats.slice(i,i+2),settled=await Promise.allSettled(batch.map(w=>routeWithWps(a,b,w)));for(const x of settled){if(x.status!=='fulfilled')continue;const r=x.value,h=schoolHitInfos(r);if(!h.length)return r;if(routeScore(r)<routeScore(best))best=r}await yieldBrowser(0)}return best}
function localPatterns(r,hit,pass){const c=r.geometry.coordinates,i=hit.segmentIndex,a={lon:c[Math.max(0,i-8)][0],lat:c[Math.max(0,i-8)][1]},b={lon:c[Math.min(c.length-1,i+10)][0],lat:c[Math.min(c.length-1,i+10)][1]},h=bearing(a,b),s=hit.s,out=[],margins=pass<2?[700,1100]:pass<4?[1200,1800]:[2200,3200];for(const side of[1,-1])for(const m of margins){const d=VALIDATION_RADIUS_M+m;out.push([135,95,55,25].map(ang=>destinationPoint(s.lon,s.lat,d,h+side*ang)))}return out}
async function localClean(a,b,start){let current={r:start,wps:[]};for(let pass=0;pass<6;pass++){const hits=schoolHitInfos(current.r);if(!hits.length)return current.r;progress(77+pass*2.5,'Refining school detours',hits.length+' remaining conflict'+(hits.length===1?'':'s'));const target=hits[0],patterns=localPatterns(current.r,target,pass),cands=[];for(let i=0;i<patterns.length;i+=2){const settled=await Promise.allSettled(patterns.slice(i,i+2).map(extra=>{const wps=[...current.wps,...extra];if(wps.length>30)return Promise.reject(Error('too many waypoints'));return routeWithWps(a,b,wps).then(r=>({r,wps}))}));for(const x of settled)if(x.status==='fulfilled')cands.push(x.value);await yieldBrowser(0)}const clean=cands.filter(x=>!schoolHitInfos(x.r).length).sort((x,y)=>x.r.duration-y.r.duration);if(clean.length)return clean[0].r;if(!cands.length)break;cands.sort((x,y)=>routeScore(x.r)-routeScore(y.r));if(routeScore(cands[0].r)>=routeScore(current.r)&&pass>=2)break;current=cands[0]}return null}
function destinationConflict(b){let nearest=null,d=Infinity;for(const s of schools){const x=distanceMeters(b,{lat:s.lat,lon:s.lon});if(x<d){d=x;nearest=s}}return nearest&&d<=VALIDATION_RADIUS_M?{s:nearest,d}:null}
function safeApproachPoint(a,b,conf){const fromSchool=bearing({lat:conf.s.lat,lon:conf.s.lon},a);return destinationPoint(conf.s.lon,conf.s.lat,VALIDATION_RADIUS_M+180,fromSchool)}
async function avoidRoute(a,b,alternatives){if(!$('avoid').checked){const r=alternatives.slice().sort((x,y)=>x.duration-y.duration)[0];return{r,n:0}}const dc=destinationConflict(b);if(dc){const safe=safeApproachPoint(a,b,dc);try{const alts=await route(a,safe,[],true),newSchools=await loadSchools(alts[0]),m=new Map;for(const s of[...schools,...newSchools])m.set(s.id,s);schools=[...m.values()];const r=await globalCorridorSearch(a,safe,alts),clean=!schoolHitInfos(r).length?r:await localClean(a,safe,r);if(clean&&!schoolHitInfos(clean).length){clean._safeApproach={original:b,point:safe,school:dc.s.name,reason:'Destination is inside a mapped 1,000 ft school zone'};return{r:clean,n:0,safeApproach:true}}}catch(e){console.warn('safe approach failed',e)}return{r:null,n:1,destinationBlocked:true,school:dc.s.name}}for(const r of alternatives)if(!schoolHitInfos(r).length)return{r,n:0};const corridor=await globalCorridorSearch(a,b,alternatives);if(corridor&&!schoolHitInfos(corridor).length)return{r:corridor,n:0};const clean=await localClean(a,b,corridor);if(clean&&!schoolHitInfos(clean).length)return{r:clean,n:0};return{r:null,n:Math.max(1,schoolHitInfos(corridor||alternatives[0]).length)}}
function drawSchools(r){schoolLayer.clearLayers();if(!r)return;const b=routeBoundsFast(r),padLat=1400/110540,padLon=1400/Math.max(20000,metersPerLon((b.minLat+b.maxLat)/2));for(const s of schools){if(s.lon<b.minLon-padLon||s.lon>b.maxLon+padLon||s.lat<b.minLat-padLat||s.lat>b.maxLat+padLat)continue;L.circle([s.lat,s.lon],{radius:VALIDATION_RADIUS_M,color:'#D93025',weight:2.5,fillColor:'#EA4335',fillOpacity:.13}).bindPopup('<b>'+s.name+'</b><br>1,000 ft school exclusion zone').addTo(schoolLayer)}}
function drawRoute(r,a,b){routeLayer.clearLayers();markerLayer.clearLayers();if(!r)return;const ll=r.geometry.coordinates.map(p=>[p[1],p[0]]);L.polyline(ll,{color:'#082d67',weight:16,opacity:.72,lineCap:'round',lineJoin:'round'}).addTo(routeLayer);L.polyline(ll,{color:'#fff',weight:12,opacity:1,lineCap:'round',lineJoin:'round'}).addTo(routeLayer);L.polyline(ll,{color:'#0b69ff',weight:8,opacity:1,lineCap:'round',lineJoin:'round'}).addTo(routeLayer);L.circleMarker([a.lat,a.lon],{radius:8,color:'#fff',weight:3,fillColor:'#0b69ff',fillOpacity:1}).addTo(markerLayer);const end=r._safeApproach?r._safeApproach.point:b;L.marker([end.lat,end.lon]).addTo(markerLayer);map.fitBounds(ll,{padding:[40,40]});drawSchools(r)}
function miles(m){return(m/1609.344).toFixed(1)+' mi'}
function time(s){const m=Math.round(s/60);return m<60?m+' min':Math.floor(m/60)+'h '+m%60+'m'}