/* v11.4 geocoding: Census for numbered addresses + semantic POI matching. */
(function(){
  const cache=new Map(),CACHE_MS=180000;
  function norm(s){return(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\bairforce\b/g,'air force').replace(/\bafb\b/g,'air force base').replace(/\bmac dill\b/g,'macdill').replace(/[^a-z0-9]+/g,' ').trim()}
  function qNumber(q){return(norm(q).match(/\b\d{1,6}\b/)||[])[0]||null}
  function isMacDillBase(q){const n=norm(q);return n.includes('macdill')&&(n.includes('air force')||n.includes('base'))}
  function hasFlorida(q){return/\b(florida|fl)\b/.test(norm(q))}
  function biasPoint(){try{if(typeof SO!=='undefined'&&SO&&Number.isFinite(SO.lat))return SO;if(typeof SD!=='undefined'&&SD&&Number.isFinite(SD.lat))return SD;if(typeof activeOrigin!=='undefined'&&activeOrigin&&Number.isFinite(activeOrigin.lat))return activeOrigin}catch(_){}return{lat:27.95,lon:-82.46}}
  function distanceKm(a,b){if(!a||!b)return 9999;const R=6371,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(h)))}
  async function census(q){if(!qNumber(q))return[];const u=new URL('https://geocoding.geo.census.gov/geocoder/locations/onelineaddress');u.searchParams.set('address',q);u.searchParams.set('benchmark','Public_AR_Current');u.searchParams.set('format','json');const d=await j(u.toString(),{},9000);return(d.result?.addressMatches||[]).map((m,i)=>{const a=m.addressComponents||{},c=m.coordinates||{},city=a.city||'',state=a.state||'',zip=a.zip||'';return{lat:+c.y,lon:+c.x,display_name:m.matchedAddress||q,address:{house_number:(m.matchedAddress||'').match(/^\s*(\d+)/)?.[1]||'',road:[a.preDirection,a.streetName,a.suffixType,a.suffixDirection].filter(Boolean).join(' '),city,state,postcode:zip},type:'address',_source:'census',_score:30-i}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon))}
  function photonCandidate(f){const p=f.properties||{},c=f.geometry?.coordinates||[],line=[p.housenumber,p.street].filter(Boolean).join(' ')||p.name||p.street||'Location',city=p.city||p.town||p.village||p.county||'',state=p.state||'',zip=p.postcode||'';return{lat:+c[1],lon:+c[0],display_name:[line,city,state,zip].filter(Boolean).join(', '),address:{house_number:p.housenumber||'',road:p.street||p.name||'',city,state,postcode:zip},type:p.type||p.osm_value||'place',_source:'photon'}}
  async function photon(q,bias){const u=new URL('https://photon.komoot.io/api/');u.searchParams.set('q',q);u.searchParams.set('limit','10');u.searchParams.set('lang','en');if(bias){u.searchParams.set('lat',bias.lat);u.searchParams.set('lon',bias.lon)}const d=await j(u.toString(),{},8500);return(d.features||[]).map(photonCandidate).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon))}
  async function nominatim(q,bias){let url='https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=10&countrycodes=us&q='+encodeURIComponent(q);if(bias&&!/\b(california|texas|new york|georgia|florida|fl|ca|tx|ny|ga)\b/.test(norm(q))){const span=3.5;url+='&viewbox='+[bias.lon-span,bias.lat+span,bias.lon+span,bias.lat-span].join(',')}const d=await j(url,{},9000);return(d||[]).map(x=>({...x,lat:+x.lat,lon:+x.lon,_source:'nominatim'}))}
  const STOP=new Set(['the','of','at','in','on','and','street','st','road','rd','drive','dr','avenue','ave','boulevard','blvd','lane','ln','court','ct','way','highway','hwy','florida','fl','tampa','brooksville']);
  function words(s){return norm(s).split(/\s+/).filter(x=>x&&!STOP.has(x))}
  function score(c,q,bias){if(Number.isFinite(c._score))return c._score;const qn=norm(q),ln=norm(c.display_name),qw=words(q),lw=new Set(words(c.display_name));let s=0,m=0;for(const w of qw){if(lw.has(w)){s+=2.4;m++}else if([...lw].some(x=>x.startsWith(w)||w.startsWith(x)))s+=.5;else s-=1.6}if(qw.length)s+=4*(m/qw.length);const qnumb=qNumber(q),cn=norm(c.address?.house_number||'');if(qnumb){if(cn===qnumb)s+=8;else if(cn)s-=10;else s-=2}const state=norm(c.address?.state||'');if(!/\b(california|texas|new york|georgia|north carolina|south carolina|virginia|washington)\b/.test(qn)){if(state.includes('florida')||state==='fl')s+=4;else if(state)s-=5}if(isMacDillBase(q)){if(/macdill/.test(ln))s+=7;if(/\b(air force|afb|base|dale mabry gate|visitor control)\b/.test(ln))s+=7;if(/\bpark\b/.test(ln))s-=20}if(bias){const km=distanceKm(bias,c);if(km<100)s+=2;s-=Math.min(5,Math.log1p(km)/1.7)}return s}
  function dedupe(list){const out=[],seen=new Set();for(const c of list){if(!Number.isFinite(c.lat)||!Number.isFinite(c.lon))continue;const k=Math.round(c.lat*1e5)+':'+Math.round(c.lon*1e5);if(seen.has(k))continue;seen.add(k);out.push(c)}return out}
  function semanticallyAcceptable(c,q){const ln=norm(c.display_name);if(isMacDillBase(q)){if(/\bpark\b/.test(ln))return false;return/macdill/.test(ln)||/6911 s dale mabry/.test(ln)||/6901 s dale mabry/.test(ln)}const num=qNumber(q);if(num&&c.address?.house_number)return norm(c.address.house_number)===num;return true}
  async function canonicalMacDill(){const qs=['6911 S Dale Mabry Hwy, Tampa, FL 33621','6901 S Dale Mabry Hwy, Tampa, FL 33621','MacDill Air Force Base Dale Mabry Gate, Tampa, Florida'],bias={lat:27.86,lon:-82.50};let all=[];for(const q of qs){try{all.push(...await census(q))}catch(_){}try{all.push(...await photon(q,bias))}catch(_){}try{all.push(...await nominatim(q,bias))}catch(_){}const good=dedupe(all).find(c=>distanceKm(c,bias)<12);if(good)return[{...good,display_name:'MacDill AFB – Dale Mabry Gate, 6911 S Dale Mabry Hwy, Tampa, FL 33621',address:{...(good.address||{}),road:'S Dale Mabry Hwy',city:'Tampa',state:'Florida',postcode:'33621'},_score:50,_canonical:'macdill'}]}return[]}
  async function smartSearch(q){q=(q||'').trim();if(q.length<2)return[];const key=norm(q),old=cache.get(key);if(old&&Date.now()-old.ts<CACHE_MS)return old.data;if(isMacDillBase(q)){const c=await canonicalMacDill();if(c.length){cache.set(key,{ts:Date.now(),data:c});return c}}const bias=biasPoint();let all=[];if(qNumber(q)){try{all.push(...await census(q))}catch(_){}if(!hasFlorida(q)){try{all.push(...await census(q+', Florida'))}catch(_){}}}try{all.push(...await photon(q,bias))}catch(_){}try{all.push(...await nominatim(q,bias))}catch(_){}if(!all.length&&!hasFlorida(q)){try{all.push(...await photon(q+', Florida',bias))}catch(_){}try{all.push(...await nominatim(q+', Florida',bias))}catch(_){}}let ranked=dedupe(all).map(c=>({...c,_score:score(c,q,bias)})).filter(c=>semanticallyAcceptable(c,q)).sort((a,b)=>b._score-a._score);if(qNumber(q)&&!ranked.length){const core=words(q).filter(w=>!/^[0-9]+$/.test(w));ranked=dedupe(all).map(c=>({...c,_score:score(c,q,bias)})).filter(c=>{const ln=norm(c.display_name),state=norm(c.address?.state||''),sameStreet=core.filter(w=>w.length>3).slice(0,2).every(w=>ln.includes(w));return sameStreet&&(state.includes('florida')||state==='fl')}).sort((a,b)=>b._score-a._score)}ranked=ranked.slice(0,8);cache.set(key,{ts:Date.now(),data:ranked});return ranked}
  searchAddr=smartSearch;
  resolve=async function(q,s){if(s)return s;const list=await smartSearch(q);if(!list.length)throw Error('No reliable nearby match found. Please choose a suggestion.');const best=list[0];if(isMacDillBase(q)&&best._canonical!=='macdill')throw Error('MacDill AFB could not be resolved to the Dale Mabry Gate.');return{lat:+best.lat,lon:+best.lon,label:best.display_name,approximate:best._score<8}}
  function rebind(k){const inp=$(k),box=$(k+'s');inp.oninput=()=>{k==='o'?SO=null:SD=null;clearTimeout(timers[k]);const q=inp.value.trim();if(q.length<3){box.style.display='none';return}timers[k]=setTimeout(async()=>{try{const list=await smartSearch(q);box.innerHTML='';for(const x of list){const[a,b]=labelAddr(x),e=document.createElement('div');e.className='item';const approx=(qNumber(q)&&!x.address?.house_number)?' · nearby street match':'';e.innerHTML='<b>'+a+'</b><small>'+b+approx+'</small>';e.onclick=()=>{const v={lat:+x.lat,lon:+x.lon,label:x.display_name};k==='o'?SO=v:SD=v;inp.value=x._canonical==='macdill'?'MacDill AFB – Dale Mabry Gate':a+(b?', '+b:'');box.style.display='none'};box.appendChild(e)}box.style.display=list.length?'block':'none'}catch(_){box.style.display='none'}},280)}}
  rebind('o');rebind('d');
})();