
const R=304.8,$=x=>document.getElementById(x);
const map=L.map('map').setView([27.9506,-82.4572],10);
let googleMap=null,googleActive=false,googleSchoolOverlays=[],googleRouteOverlay=null,googleMarkers=[],googleGpsMarker=null,googleGpsCircle=null;
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
const sl=L.layerGroup().addTo(map),rl=L.layerGroup().addTo(map),ml=L.layerGroup().addTo(map),gl=L.layerGroup().addTo(map);
let schools=[],SO=null,SD=null,AR=null,AD=null,W=null,timers={},progressTimer=null,progressStart=0,currentPos=null,lastGpsReroute=0,isRerouting=false,startExemptKeys=new Set(),destExemptKeys=new Set();
function stat(t,c=''){$('st').className='status '+c;$('st').innerHTML=t}
function setProgress(p,stage,detail=''){$('progressWrap').style.display='block';p=Math.max(0,Math.min(100,p));$('progressFill').style.width=p+'%';$('progressPct').textContent=Math.round(p)+'%';$('progressStage').textContent=stage;$('progressDetail').textContent=detail||stage}
function startProgress(){clearInterval(progressTimer);progressStart=Date.now();$('elapsed').textContent='0s';setProgress(3,'Starting route calculation','Preparing');progressTimer=setInterval(()=>$('elapsed').textContent=Math.round((Date.now()-progressStart)/1000)+'s',1000)}
function endProgress(ok=true){clearInterval(progressTimer);if(ok)setProgress(100,'Route ready','Validation complete')}
function failProgress(msg){clearInterval(progressTimer);$('progressFill').style.background='#b91c1c';$('progressStage').textContent='Could not complete route';$('progressDetail').textContent=msg}
function resetProgressColor(){$('progressFill').style.background='#2563eb'}
async function j(url,opt={},ms=22000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...opt,signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch(e){if(e.name==='AbortError')throw Error('Request timed out');throw e}finally{clearTimeout(t)}}
async function addr(q){return j('https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=6&countrycodes=us&q='+encodeURIComponent(q),{},12000)}
function pa(x){let a=x.address||{},x1=[a.house_number,a.road].filter(Boolean).join(' ')||x.display_name.split(',')[0];let x2=[a.city||a.town||a.village||a.county,a.state,a.postcode].filter(Boolean).join(', ');return[x1,x2]}
function ac(k){const i=$(k),b=$(k+'s');i.oninput=()=>{k==='o'?SO=null:SD=null;clearTimeout(timers[k]);const q=i.value.trim();if(q.length<3){b.style.display='none';return}timers[k]=setTimeout(async()=>{try{const z=await addr(q);b.innerHTML='';z.forEach(x=>{const p=pa(x),e=document.createElement('div');e.className='it';e.innerHTML='<b>'+p[0]+'</b><small>'+p[1]+'</small>';e.onclick=()=>{const v={lat:+x.lat,lon:+x.lon,label:x.display_name};k==='o'?SO=v:SD=v;i.value=p[0]+(p[1]?', '+p[1]:'');b.style.display='none'};b.appendChild(e)});b.style.display=z.length?'block':'none'}catch(e){console.warn('autocomplete',e)}},300)}}
ac('o');ac('d');document.addEventListener('click',e=>{if(!e.target.closest('.field')){$('os').style.display='none';$('ds').style.display='none'}});
async function resolve(q,s){if(s)return s;const z=await addr(q);if(!z.length)throw Error('Address not found: '+q);return{lat:+z[0].lat,lon:+z[0].lon,label:z[0].display_name}}
function getGpsPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('GPS/geolocation is not available in this browser.'));navigator.geolocation.getCurrentPosition(p=>{currentPos={lat:p.coords.latitude,lon:p.coords.longitude,label:'Current location',accuracy:p.coords.accuracy||0};resolve(currentPos)},e=>reject(Error(e.message||'Could not get current location.')),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})})}
async function useMyLocation(){try{stat('Getting your current GPS location…');const p=await getGpsPosition();SO=p;$('o').value='Current location';gl.clearLayers();L.circleMarker([p.lat,p.lon],{radius:8,color:'#1d4ed8',fillColor:'#3b82f6',fillOpacity:1,weight:3}).addTo(gl);if(p.accuracy)L.circle([p.lat,p.lon],{radius:p.accuracy,color:'#60a5fa',weight:1,fillOpacity:.05}).addTo(gl);if(googleActive)drawGoogleGps(p.lat,p.lon,p.accuracy);setMapView(p.lat,p.lon,16);stat('Current location selected.','ok');return p}catch(e){stat('Could not get current location: '+e.message,'warn');throw e}}
function pointInSchool(p,s){try{return turf.booleanPointInPolygon(turf.point([p.lon,p.lat]),zone(s))}catch(_){return false}}
function refreshEndpointExemptions(a,b){startExemptKeys=new Set();destExemptKeys=new Set();for(const s of schools){if(pointInSchool(a,s))startExemptKeys.add(schoolKey(s));if(pointInSchool(b,s))destExemptKeys.add(schoolKey(s))}}
function avoidableHits(r,a,b){const raw=hits(r);return raw.filter(s=>{const k=schoolKey(s);return !startExemptKeys.has(k)&&!destExemptKeys.has(k)})}
function routeOffDistanceMeters(lat,lon){if(!AR)return Infinity;try{return turf.pointToLineDistance(turf.point([lon,lat]),turf.lineString(AR.geometry.coordinates),{units:'kilometers'})*1000}catch(_){return Infinity}}
async function routes(a,b,alt=true,w=[]){const pts=[a,...w,b],c=pts.map(p=>p.lon+','+p.lat).join(';');const tail='/'+c+'?overview=full&geometries=geojson&steps=true&alternatives='+(alt?'true':'false');const urls=['https://router.project-osrm.org/route/v1/driving'+tail,'https://routing.openstreetmap.de/routed-car/route/v1/driving'+tail];let errs=[];for(let u of urls){try{const z=await j(u,{},22000);if(z.routes?.length)return z.routes;errs.push('no route')}catch(e){errs.push(e.message)}}throw Error('Routing service unavailable: '+errs.join(' / '))}
function routeOptions(){const u=document.querySelector('input[name="units"]:checked')?.value||'auto';return{schools:$('avoidSchools').checked,highways:$('avoidHighways').checked,tolls:$('avoidTolls').checked,ferries:$('avoidFerries').checked,units:u}}
function googleLoadScript(key){return new Promise((resolve,reject)=>{if(window.google?.maps)return resolve();window.__schoolGpsGoogleReady=()=>resolve();const s=document.createElement('script');s.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&libraries=places&v=weekly&callback=__schoolGpsGoogleReady';s.async=true;s.defer=true;s.onerror=()=>reject(Error('Google Maps could not be loaded. Check the API key and allowed referrers.'));document.head.appendChild(s)})}
function setupGoogleAutocomplete(inputId,which){const ac=new google.maps.places.Autocomplete($(inputId),{componentRestrictions:{country:'us'},fields:['geometry','formatted_address','name']});ac.addListener('place_changed',()=>{const p=ac.getPlace();if(!p.geometry?.location)return;const v={lat:p.geometry.location.lat(),lon:p.geometry.location.lng(),label:p.formatted_address||p.name||'Selected place'};if(which==='o')SO=v;else SD=v;$(inputId).value=v.label})}
async function enableGoogle(){const key=$('googleKey').value.trim();if(!key){$('googleStatus').textContent='Paste your Google Maps Platform API key first.';return}$('googleEnable').disabled=true;$('googleStatus').textContent='Loading Google Maps and Places…';try{await googleLoadScript(key);localStorage.setItem('schoolGpsGoogleKey',key);googleActive=true;$('map').style.display='none';$('gmap').style.display='block';googleMap=new google.maps.Map($('gmap'),{center:{lat:27.9506,lng:-82.4572},zoom:10,mapTypeControl:false,streetViewControl:false,fullscreenControl:false});setupGoogleAutocomplete('o','o');setupGoogleAutocomplete('d','d');$('googleStatus').textContent='Google Maps + Places active for this browser.';if(schools.length)drawS();if(AR)drawR(AR,SO||currentPos||{lat:27.95,lon:-82.45},AD||SD||{lat:27.95,lon:-82.45});if(currentPos)drawGoogleGps(currentPos.lat,currentPos.lon,currentPos.accuracy||0)}catch(e){$('googleStatus').textContent=e.message||String(e)}finally{$('googleEnable').disabled=false}}
function clearGoogleSchools(){googleSchoolOverlays.forEach(x=>x.setMap(null));googleSchoolOverlays=[]}
function polygonToGooglePaths(feature){const g=feature.geometry;const conv=ring=>ring.map(p=>({lat:p[1],lng:p[0]}));if(g.type==='Polygon')return[g.coordinates.map(conv)];if(g.type==='MultiPolygon')return g.coordinates.map(poly=>poly.map(conv));return[]}
function drawGoogleSchools(){if(!googleActive||!googleMap)return;clearGoogleSchools();for(const s of schools){try{const z=zone(s);for(const paths of polygonToGooglePaths(z)){const poly=new google.maps.Polygon({paths,strokeColor:'#b91c1c',strokeOpacity:.9,strokeWeight:1,fillColor:'#ef4444',fillOpacity:.15,map:googleMap});googleSchoolOverlays.push(poly)}}catch(_){}}}
function drawGoogleRoute(r,a,b){if(!googleActive||!googleMap)return;if(googleRouteOverlay)googleRouteOverlay.setMap(null);googleMarkers.forEach(m=>m.setMap(null));googleMarkers=[];const path=r.geometry.coordinates.map(c=>({lat:c[1],lng:c[0]}));googleRouteOverlay=new google.maps.Polyline({path,strokeColor:'#111827',strokeOpacity:.95,strokeWeight:6,map:googleMap});googleMarkers.push(new google.maps.Marker({position:{lat:a.lat,lng:a.lon},map:googleMap,title:'Start'}));googleMarkers.push(new google.maps.Marker({position:{lat:b.lat,lng:b.lon},map:googleMap,title:'Destination'}));const bounds=new google.maps.LatLngBounds();path.forEach(p=>bounds.extend(p));googleMap.fitBounds(bounds,40)}
function drawGoogleGps(lat,lon,accuracy=0){if(!googleActive||!googleMap)return;if(googleGpsMarker)googleGpsMarker.setMap(null);if(googleGpsCircle)googleGpsCircle.setMap(null);googleGpsMarker=new google.maps.Marker({position:{lat,lng:lon},map:googleMap,title:'Current location'});if(accuracy)googleGpsCircle=new google.maps.Circle({center:{lat,lng:lon},radius:accuracy,strokeColor:'#60a5fa',strokeWeight:1,fillColor:'#60a5fa',fillOpacity:.05,map:googleMap})}
function setMapView(lat,lon,zoom=16){if(googleActive&&googleMap){googleMap.setCenter({lat,lng:lon});googleMap.setZoom(zoom)}else map.setView([lat,lon],zoom)}
